import Head from "next/head";
import { useState } from "react";
import { Inter } from "next/font/google";
import confetti from "canvas-confetti";
import toast from "react-hot-toast";

const inter = Inter({
  weight: ["400", "900", "600", "500"],
  display: "swap",
  subsets: ["latin"],
});

import { Hero, Navbar, Reasons, Generated } from "@/components";

export default function Home() {
  const [promptValue, setPromptValue] = useState("");
  const [generated, setGenerated] = useState("");
  const [loader, setLoader] = useState("Generate");

  const prompt = `I will give you a sentence, Please correct it or rewrite it to a professional manner, the following sentence is: "${promptValue}"`;

  const generating = async () => {
    setLoader("Generating...");
    const res = await fetch("/api/hello", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ prompt }),
    });

    const data = await res.json();

    setGenerated(data.choices[0].text);
    confetti();
    setLoader("Generate Again");
  };

  const copingText = (value: string) => {
    navigator.clipboard.writeText(value);
    toast("✅ Copied");
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className} p-4`}>
        <Navbar />

        <Hero
          promptValue={promptValue}
          setPromptValue={setPromptValue}
          generating={generating}
          loader={loader}
        />

        {generated.length !== 0 && (
          <Generated
            promptValue={promptValue}
            generated={generated}
            setGenerated={setGenerated}
            copingText={copingText}
          />
        )}

        <Reasons />
      </main>
    </>
  );
}
